import React from "react";
import {
  Grid,
  TableCell,
  TableHead,
  TableRow,
  Table,
  Paper,
  TableBody,
  Button,
  makeStyles,
} from "@material-ui/core";
import EditOutlinedIcon from "@material-ui/icons/EditOutlined";
import DeleteForeverOutlinedIcon from "@material-ui/icons/DeleteForeverOutlined";
import { useEffect, useState } from "react";

const useStyles = makeStyles((theme) => ({
  btn_margin: {
    marginLeft: "16px",
  },
}));

const GraphsPannel = () => {
  //   const [summaries, setUsers] = useState([]);
  //   const [summaries, setSummaries] = useState([]);
  const [graphs, setGraphs] = useState([]);

  useEffect(() => {
    fetch("http://localhost:8080/all_wind_graphs")
      .then((response) => response.json())
      .then((results) => setGraphs(results));
    return () => {};
  });

  const classes = useStyles();
  return (
    <Grid container spacing={3}>
      <Grid item xs={12}>
        <Paper>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>
                  <strong>S/N</strong>
                </TableCell>
                <TableCell>
                  <strong>GRAPH NAME</strong>
                </TableCell>
                <TableCell>
                  <strong>GENERATED BY</strong>
                </TableCell>
                <TableCell align="center">
                  <strong>PATH</strong>
                </TableCell>
                <TableCell>
                  <strong>ISSUE DATE</strong>
                </TableCell>
                <TableCell align="center">
                  <strong>ACTION</strong>
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {graphs.map((data, index) => {
                return (
                  <TableRow key={index}>
                    <TableCell component="th" scope="row">
                      {index + 1}
                    </TableCell>
                    <TableCell>{data.name}</TableCell>
                    <TableCell>
                      {data.firstname} {data.lastname}
                    </TableCell>
                    <TableCell>{data.graph}</TableCell>
                    <TableCell>{data.issued_at}</TableCell>
                    <TableCell align="center">
                      <Button
                        variant="outlined"
                        color="primary"
                        startIcon={<EditOutlinedIcon />}
                      >
                        Modify
                      </Button>
                      <Button
                        variant="outlined"
                        color="secondary"
                        startIcon={<DeleteForeverOutlinedIcon />}
                        className={classes.btn_margin}
                      >
                        Remove
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </Paper>
      </Grid>
    </Grid>
  );
};

export default GraphsPannel;
